#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/slcc_updater'

puts "Process Start: #{Time.now}"
SLCCalendar::Updater.new.force_register ARGV[0]
puts "Process Finished: #{Time.now}"
