#!/usr/bin/env ruby

require_relative 'slc_calendar_updater.rb'

puts "Process Start: " + Time.now.to_s
puts "# Update by tweet"
SLCCalendar::CalendarUpdater.new.update_by_tweets
puts "Process Finished: " + Time.now.to_s
