#!/usr/bin/env ruby

require_relative 'lib/slcc_updater'

puts 'Process Start: ' + Time.now.to_s
puts '# Update by tweet'
SLCCalendar::Updater.new.update_by_tweets
puts 'Process Finished: ' + Time.now.to_s
