#!/usr/bin/env ruby

require_relative 'lib/slcc_updater.rb'

puts "Process Start: " + Time.now.to_s
puts "# Update existing schedules"
SLCCalendar::Updater.new.update_registered_events
puts "Process Finished: " + Time.now.to_s
