#!/usr/bin/env ruby

require_relative 'slc_calendar_updater.rb'

puts "Process Start: " + Time.now.to_s
puts "# Update existing schedules"
SLCCalendar::CalendarUpdater.new.update_registered_events
puts "Process Finished: " + Time.now.to_s
