#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/slcc_updater'

puts "Process Start: #{Time.now}"

puts '# Update existing schedules'
SLCCalendar::Updater.new.update_registered_events

puts "Process Finished: #{Time.now}"
